[package]
name = "watchcrab"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10.64", features = ["vendored"] }
reqwest = { version = "0.12.3", features = ["json"] }
serde = { version = "1.0.197", features = ["serde_derive"] }
tokio = "1.37.0"
toml = "0.8.12"
